services:
  - type: web
    name: hockey-stats-webapp
    runtime: python
    buildCommand: pip install -r hockey_stats_webapp/requirements.txt
    startCommand: gunicorn hockey_stats_webapp.app:server
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: HOCKEY_STATS_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
